# This config file contains general information about 
# your project, such as its name, the root folder, 
# the output ROM path, etc.

# All config files use the TOML (https://toml.io/en/) format!

[output]

# Path for the output ROM
output_rom = "build/{project_name}.smc"

# Path for BPS package output by the Package function
bps_package = "build/package/{project_name}.bps"

# Path to temporary folder used during builds
temporary_folder = "build/temp"


[settings]

# Root directory of the project, this can 
# be a relative or absolute path, but relative 
# paths are generally nicer since they will stay 
# valid even if you move your project folder
project_root = ".."

# Where callisto should check for conflicts 
# between tools/resources during rebuilds, 
# can be set to "none" to disable it, "hijacks" 
# to only check for conflicts in the vanilla 
# ROM area or "all" to check anywhere in the ROM
check_conflicts = "hijacks"

# Optional log file for conflicts, if 
# set, callisto will log conflicts to this 
# file instead of the console after rebuilds
conflict_log_file = "conflicts.txt"

# Set to false to disable automatic exports from Lunar Magic
enable_automatic_exports = true

# Any symbols from the build order (see build_order.toml)
# listed here will not be considered when 
# reporting conflicts, this lets you configure the verbosity 
# of callisto's conflict reporting to your liking
ignored_conflict_symbols = [
	"InitialPatch",

    "Overworld",
    "TitleScreen",
    "Credits",
    "GlobalExAnimation",

    "SharedPalettes",

    "ExGraphics",
    "Graphics",

    "Levels",

    "Map16"
]

# Set to true to use integrated text-based map16 format 
# instead of Lunar Magic's binary .map16 format
# (git handles the text-based one much better)
use_text_map16_format = true
