# This config file contains the header file for and list of 
# modules to be inserted by callist during the build process

# Modules are extremely general constructs that can be used to 
# add new functionality to a ROM that can be accessed by *any* 
# tool, sprite, block, etc. without any code duplication or 
# file duplication. They can contain data or code, anything 
# you want really. Think of them like UberASM library files or 
# GPS/PIXI routines, but usable *anywhere*!

# For more details, check the documentation!

[resources]

# File that is incsrc'd just prior to any module during insertion
# May be useful for SA-1 defines and similar stuff
module_header = "path/to/my/header.asm"


# List of modules to insert
modules = [
    # { input_path = "resources/modules/binary/uncompressed_exgfx.bin" },
    # { input_path = "resources/modules/code/teleport.asm" },

    # { input_path = "resources/modules/binary/large_table.asm", output_paths = [ "binaries/my_large_table.asm", "other/random/place.asm" ] },
    # { input_path = "resources/modules/code/reset.asm", output_paths = [ "code/reset.asm", "code/also/accessible/here.asm"] }
]
